services:
  # Web Service (Spring Boot Application)
  - type: web
    name: spring-board-app
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: board-postgres
          property: connectionString
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx512m -Xms256m"

databases:
  - name: board-postgres
    plan: free
    databaseName: boarddb
    user: boarduser
